#!/bin/bash /etc/rc.common

START=99
PNAME="auto-auth:S"
USERID=190000000000
PWD=1234
stop() {
    PID=$(ps | grep ${PNAME} | grep -v grep | awk '{print $1}')
    if [ -n "$PID" ]; then
        kill $PID
    fi
}
start() {
    stop
    logger -t autoauth -p user.info "HELLO!"
    /etc/autoauth.sh ${USERID} ${PWD} ${PNAME} &
}
restart() {
    stop
    start
}
