#!/bin/sh /etc/rc.common

START=60
PNAME="autoauth.sh"
stop() {
    killall -q ${PNAME}
}
start() {
    stop
    logger -t "autoauth" -p user.info "HELLO!"
    /etc/${PNAME} &
}
restart() {
    stop
    start
}
